module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#34343d",
        "surface-dim": "#13131a",
        "on-primary": "#00354a",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#e4e1ec",
        "surface-container-high": "#2a2932",
        "surface-bright": "#393841",
        "error-container": "#93000a",
        "inverse-primary": "#00668a",
        "surface-container-low": "#1b1b23",
        "on-surface": "#e4e1ec",
        "secondary-container": "#592da2",
        "tertiary-fixed-dim": "#c4c1fb",
        "surface-container": "#1f1f27",
        "secondary-fixed": "#ebdcff",
        "on-background": "#e4e1ec",
        "outline": "#87929a",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#2d2a5b",
        "secondary-fixed-dim": "#d3bbff",
        "outline-variant": "#3e484f",
        "tertiary-container": "#afabe4",
        "background": "#13131a",
        "tertiary": "#cbc7ff",
        "inverse-on-surface": "#302f38",
        "on-secondary-container": "#c8aaff",
        "primary-container": "#38bdf8",
        "surface-container-lowest": "#0e0d15",
        "surface": "#13131a",
        "on-primary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#572ba0",
        "on-secondary": "#3f0689",
        "tertiary-fixed": "#e3dfff",
        "on-primary-container": "#004965",
        "primary-fixed": "#c4e7ff",
        "error": "#ffb4ab",
        "surface-tint": "#7bd0ff",
        "on-tertiary-fixed-variant": "#444173",
        "on-primary-fixed-variant": "#004c69",
        "primary": "#8ed5ff",
        "secondary": "#d3bbff",
        "on-tertiary-container": "#413e6f",
        "on-secondary-fixed": "#260059",
        "surface-variant": "#34343d",
        "on-tertiary-fixed": "#181445",
        "on-error": "#690005",
        "primary-fixed-dim": "#7bd0ff",
        accent: '#4F46E5',
        dark: '#0F172A',
        void: '#030308',
        'void-card': '#0e0d15',
        'void-surface': '#13131a',
        'void-elevated': '#1b1b23',
        'void-border': 'rgba(255, 255, 255, 0.08)',
        'cyan-stellar': '#38bdf8',
        'cyan-bright': '#8ed5ff',
        'violet-astral': '#8b5cf6',
        'violet-light': '#d3bbff',
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Grotesk", "sans-serif"],
        sans: ["Hanken Grotesk", "Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.015em", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "code-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "0em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" }]
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "0.75rem",
        "gutter": "1.5rem",
        "margin": "2rem",
        "margin-mobile": "1rem"
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))'
      },
      animation: {
        'spin-slow': 'spin 18s linear infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'shimmer': 'shimmer 4s ease-in-out infinite',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { opacity: '0.4', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.05)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        }
      }
    }
  },
  plugins: []
};